import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import { AuthProvider } from "./providers";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="max-w-4xl mx-auto p-4">
          <AuthProvider>
            <Toaster/>
              <Header />
              {children}
              <footer className="border-t p-8 text-center text-gray-500 mt-16 ">
                &copy; 2024 All rights reserved
              </footer>
          </AuthProvider>
        </main>
      </body>
    </html>
  );
}
